name: Build iOS
on: [workflow_dispatch]
jobs:
  default:
    name: Build default app
    uses: ./.github/workflows/fastlane_ios.yml
    with:
      google_service_info_plist_base64: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST_BASE64 }}
    secrets: inherit
  naofood:
    name: Build Naofood app
    uses: ./.github/workflows/fastlane_ios.yml
    with:
      instance: naofood
      instance_url: https://naofood.coopcycle.org
      app_name: Naofood
      app_id: org.coopcycle.Naofood
      primary_color: "#f8781f"
      google_service_info_plist_base64: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST_BASE64_NAOFOOD }}
    secrets: inherit
