name: Build iOS
on:
  workflow_dispatch:
    inputs:
      build_official:
        description: 'Build official app'
        required: true
        type: boolean
      build_naofood:
        description: 'Build Naofood app'
        required: true
        type: boolean
jobs:
  default:
    if: ${{ inputs.build_official }}
    name: Build default app
    uses: ./.github/workflows/fastlane_ios.yml
    with:
      google_service_info_plist_base64: GOOGLE_SERVICE_INFO_PLIST_BASE64
    secrets: inherit
  naofood:
    if: ${{ inputs.build_naofood }}
    name: Build Naofood app
    uses: ./.github/workflows/fastlane_ios.yml
    with:
      instance: naofood
      instance_url: https://naofood.coopcycle.org
      app_name: Naofood
      app_id: org.coopcycle.Naofood
      primary_color: "#f8781f"
      google_service_info_plist_base64: GOOGLE_SERVICE_INFO_PLIST_BASE64_NAOFOOD
    secrets: inherit
